#!/usr/bin/env python3
"""
audit_period_attribution.py — wq-054 §4.4 audit backfill.

Walks every entity provenance entry and flags claims whose text contains a
period qualifier (H1/Q3/exit-snapshot/monthly-peak) that doesn't match the
field path they were written to. Generates data/wq-054-existing-misroutes.md.

Read-only by default. Future `--apply` mode could re-route values into the
correct sub-period field, but per brief §5 backfill conflicts are an
editorial decision — left for Simon to do manually.

Run: python3 scripts/audit_period_attribution.py
"""

import json
import os
import sys
from collections import OrderedDict, defaultdict

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from apply_decisions import detect_period_scope  # noqa: E402

ENTITIES_PATH = os.path.join(BASE_DIR, 'entities.json')
REPORT_PATH = os.path.join(BASE_DIR, 'data', 'wq-054-existing-misroutes.md')


def parse_prov_key(key):
    """Provenance keys look like '2025.collected_revenue' or 'current.employees'.
    Some sub-period keys (post-wq-054) look like '2025_h1.collected_revenue' or
    '2024.exit_arr'. Return (year_part, field_part)."""
    if '.' not in key:
        return None, key
    year_part, field_part = key.split('.', 1)
    return year_part, field_part


def field_implies_scope(year_part, field_part):
    """Detect the scope a field path implies. Mirror of resolve_field_path."""
    if year_part == 'current':
        return 'point_in_time'
    if year_part and '_' in year_part:
        # 2025_h1, 2025_q3 etc
        suffix = year_part.split('_', 1)[1]
        if suffix in ('h1', 'h2', 'q1', 'q2', 'q3', 'q4'):
            return suffix
    if field_part.startswith('exit_'):
        return 'exit_snapshot'
    if field_part.startswith('monthly_peak_'):
        return 'monthly_peak'
    return 'annual'


def audit():
    with open(ENTITIES_PATH) as f:
        entities = json.load(f)

    findings = []
    by_entity = defaultdict(list)

    for company in entities.get('companies', []):
        slug = company.get('slug')
        prov_block = company.get('provenance') or {}
        for prov_key, prov in prov_block.items():
            year_part, field_part = parse_prov_key(prov_key)
            implied_scope = field_implies_scope(year_part, field_part)
            for claim in (prov.get('claims') or []):
                # If the claim itself records its scope (post-wq-054), trust that
                stored_scope = claim.get('time_period_scope')
                if stored_scope:
                    if stored_scope != implied_scope and stored_scope != 'annual':
                        # stored as sub-period but field path says annual — misroute
                        finding = {
                            'entity': slug,
                            'prov_key': prov_key,
                            'implied_scope': implied_scope,
                            'stored_scope': stored_scope,
                            'detected_qualifier': claim.get('period_qualifier'),
                            'detection_source': 'stored',
                            'claim_id': claim.get('id'),
                            'claim_text': (claim.get('claim') or '')[:160],
                            'value': claim.get('value'),
                            'unit': claim.get('unit'),
                        }
                        findings.append(finding)
                        by_entity[slug].append(finding)
                    continue

                # Fall back to text detection
                text = claim.get('claim') or ''
                detected_scope, qualifier = detect_period_scope(text)
                if detected_scope and detected_scope != implied_scope:
                    finding = {
                        'entity': slug,
                        'prov_key': prov_key,
                        'implied_scope': implied_scope,
                        'stored_scope': None,
                        'detected_scope': detected_scope,
                        'detected_qualifier': qualifier,
                        'detection_source': 'text',
                        'claim_id': claim.get('id'),
                        'claim_text': text[:160],
                        'value': claim.get('value'),
                        'unit': claim.get('unit'),
                    }
                    findings.append(finding)
                    by_entity[slug].append(finding)

    return findings, by_entity


def write_report(findings, by_entity):
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    lines = []
    lines.append('# wq-054 — existing period-attribution misroutes')
    lines.append('')
    lines.append(f'Generated by `scripts/audit_period_attribution.py` on {__import__("datetime").date.today()}.')
    lines.append('')
    lines.append('Each row below is a provenance claim whose text contains a sub-period qualifier ')
    lines.append('(H1/Q3/exit-snapshot/monthly-peak) but was written to a field path implying a ')
    lines.append('different scope (usually annual). Per brief §5 these are NOT auto-moved — Simon ')
    lines.append('decides per-case whether to retire the value, move it to a sub-period field, ')
    lines.append('or annotate it as ambiguous.')
    lines.append('')
    lines.append(f'**Total flagged claims: {len(findings)}** across **{len(by_entity)} entit{"y" if len(by_entity)==1 else "ies"}**.')
    lines.append('')

    if not findings:
        lines.append('## ✓ No misroutes detected.')
        lines.append('')
        lines.append('All provenance claims agree with their field-path scope. No backfill needed.')
    else:
        lines.append('## Summary by entity')
        lines.append('')
        lines.append('| Entity | Flagged claims |')
        lines.append('|---|---|')
        for slug, items in sorted(by_entity.items(), key=lambda kv: -len(kv[1])):
            lines.append(f'| `{slug}` | {len(items)} |')
        lines.append('')

        lines.append('## Detail')
        lines.append('')
        for slug, items in sorted(by_entity.items()):
            lines.append(f'### {slug}')
            lines.append('')
            for f in items:
                detected = f.get('detected_scope') or f.get('stored_scope')
                qual = f.get('detected_qualifier') or '(no qualifier extracted)'
                lines.append(f'- **{f["prov_key"]}** — implied `{f["implied_scope"]}`, detected `{detected}` (qualifier: _{qual}_, source: {f["detection_source"]})')
                lines.append(f'  - claim_id: `{f["claim_id"]}`, value: {f["value"]} {f["unit"] or ""}')
                lines.append(f'  - text: _{f["claim_text"]}_')
            lines.append('')

    with open(REPORT_PATH, 'w') as f:
        f.write('\n'.join(lines))


def main():
    findings, by_entity = audit()
    write_report(findings, by_entity)
    print(f'Wrote {REPORT_PATH}')
    print(f'Total flagged claims: {len(findings)} across {len(by_entity)} entities')
    if findings:
        print('Top 5 entities by flag count:')
        for slug, items in sorted(by_entity.items(), key=lambda kv: -len(kv[1]))[:5]:
            print(f'  {slug}: {len(items)} claim(s)')


if __name__ == '__main__':
    main()
